### ISSUE TITLE
Links to help point to the IP and not the domain

### ISSUE THREAD

**Issue by SeanDS** [mattpitkin/theonlinemcmc#11]
The URL behind "model" in, for instance, "Input model equation:" points to the IP address of the server and not the domain name. Other help links also have this issue.

**Comment by mattpitkin** [comment]
Unfortunately I've had to do this for the moment as the domain name just forwards on to the server IP address (but hides the forwarding using frames). Hence, an URL to e.g. http://theonlinemcmc.com/#themodel doesn't actually point anywhere.

**Comment by SeanDS** [comment]
Ok. I think some anti-virus software can (stupidly) block direct IP addresses because some scammers use them for phishing. But I guess most users will be Mac/Linux/Windows power users who should know better?

Does AWS provide a DNS service?

**Comment by mattpitkin** [comment]
They (Google Cloud, but I imagine also AWS) do provide a DNS service, but I wasn't 100% sure how to set it up and change this with my domain name host. It is something that I'd like to do (if I don't end up hosting the site locally).
