### ISSUE TITLE
Support for ultranest

### ISSUE THREAD

**Issue by JohannesBuchner** [mattpitkin/theonlinemcmc#27]
Hi @mattpitkin,

I don't know how to open an issue with bilby, so I am putting this here.

Perhaps you want to add support for UltraNest. I am close to a stable release and am looking for people to test its correctness and performance. The documentation is here: https://johannesbuchner.github.io/UltraNest/
The usage and supported features is quite similar to pymultinest, except it is easier to install and handles more problems correctly (albeit sometimes slower). For high-d problems, there is also support for advanced MCMC schemes, such as hit-and-run Monte Carlo and dynamic HMC (an improvement over NUTS).

Cheers,
            Johannes

**Comment by mattpitkin** [comment]
Hi @JohannesBuchner, adding UltraNest into bilby sounds like a good idea. The package is looking very nice now. I can create an issue about this on the bilby repo, or you can email issues to contact+lscsoft-bilby-1846-issue-@support.ligo.org, which will open an issue that you will get notifications for.

Cc @gregoryashton

**Comment by mattpitkin** [comment]
@johannesbuchner one quick question, can you  checkpoint your runs with UltraNest? I'm guessing that you can as you seem to have a "resume" argument to the run command?

**Comment by mattpitkin** [comment]
I've created an [issue](https://git.ligo.org/lscsoft/bilby/issues/456) on the bilby repo to add UltraNest.

**Comment by JohannesBuchner** [comment]
> @JohannesBuchner one quick question, can you checkpoint your runs with UltraNest? I'm guessing that you can as you seem to have a "resume" argument to the run command?

Yes, if you give a directory with the log_dir argument, it will write to disk, and if you use resume=True it can resume.

**Comment by mattpitkin** [comment]
@JohannesBuchner I've finally got around to implementing a wrapper to UltraNest in bilby. It's not in the release version yet, but you can find the merge request with the changes [here](https://git.ligo.org/lscsoft/bilby/-/merge_requests/766). In the implementation it makes the choice between using the `NestedSampler` or `ReactiveNestedSampler` integrator if you supply a number of live points or not.

**Comment by mattpitkin** [comment]
Bilby [v0.6.8](https://pypi.org/project/bilby/) has now been released, which contains the wrapper for Ultranest, so I'll close this issue for now.
